-- cloneAvatar.lua
-- Fitur Clone Avatar untuk Vanzyxxx Modular
-- Author: Generated by AI (Fixed by Gemini)
-- Version: 2.1.0 (Fixed Floating Menu)
-- Delta Executor Compatible

return function(UI, Services, Config, Theme)
    local Players = Services.Players
    local LocalPlayer = Players.LocalPlayer
    local HttpService = Services.HttpService
    local TweenService = Services.TweenService
    
    -- Favorites storage
    local FAVORITES_FILE = "Vanzyxxx_Favorites.json"
    local MAX_FAVORITES = 20
    
    -- Default favorites
    local DEFAULT_FAVORITES = {
        {name = "panggiljee", id = 9298294077},
        {name = "icibos0325", id = 9101145665},
        {name = "imyulay", id = 4401600759}
    }
    
    local FavoritesList = {}
    local OriginalAvatar = {}
    local HasBackup = false
    
    -- Mini menu variables
    local MiniMenuLogo = nil
    local MiniMenuActive = false
    local FloatingFrame = nil -- Variable untuk menu melayang
    
    -- Effects
    local ExplosionEffect = nil
    
    -- Load favorites
    local function LoadFavorites()
        if isfile and isfile(FAVORITES_FILE) then
            local success, data = pcall(function()
                return HttpService:JSONDecode(readfile(FAVORITES_FILE))
            end)
            if success and type(data) == "table" then
                FavoritesList = data
                return
            end
        end
        FavoritesList = DEFAULT_FAVORITES
    end
    
    -- Save favorites
    local function SaveFavorites()
        if writefile then
            pcall(function()
                writefile(FAVORITES_FILE, HttpService:JSONEncode(FavoritesList))
            end)
        end
    end
    
    -- Create explosion effect
    local function CreateExplosionEffect(position)
        if ExplosionEffect then ExplosionEffect:Destroy() end
        
        ExplosionEffect = Instance.new("Part")
        ExplosionEffect.Name = "AvatarCloneExplosion"
        ExplosionEffect.Size = Vector3.new(1, 1, 1)
        ExplosionEffect.Position = position
        ExplosionEffect.Anchored = true
        ExplosionEffect.CanCollide = false
        ExplosionEffect.Transparency = 1
        ExplosionEffect.Parent = Services.Workspace
        
        local fire = Instance.new("Fire")
        fire.Size = 10
        fire.Heat = 15
        fire.Color = Color3.fromRGB(255, 100, 0)
        fire.SecondaryColor = Color3.fromRGB(255, 200, 0)
        fire.Parent = ExplosionEffect
        
        local light = Instance.new("PointLight")
        light.Brightness = 5
        light.Range = 20
        light.Color = Color3.fromRGB(255, 150, 0)
        light.Parent = ExplosionEffect
        
        local sound = Instance.new("Sound")
        sound.SoundId = "rbxassetid://138080902"
        sound.Volume = 0.5
        sound.Parent = ExplosionEffect
        sound:Play()
        
        TweenService:Create(fire, TweenInfo.new(1.5), {Size = 0}):Play()
        TweenService:Create(light, TweenInfo.new(1.5), {Brightness = 0}):Play()
        
        game:GetService("Debris"):AddItem(ExplosionEffect, 2)
    end
    
    -- Backup original avatar
    local function BackupOriginalAvatar()
        if HasBackup or not LocalPlayer.Character then return end
        
        local char = LocalPlayer.Character
        OriginalAvatar = {
            CharacterAppearanceId = LocalPlayer.CharacterAppearanceId,
            BodyColors = LocalPlayer:GetBodyColors()
        }
        
        OriginalAvatar.Clothing = {}
        for _, item in ipairs(char:GetChildren()) do
            if item:IsA("Shirt") or item:IsA("Pants") or item:IsA("ShirtGraphic") then
                table.insert(OriginalAvatar.Clothing, item:Clone())
            end
        end
        
        OriginalAvatar.Accessories = {}
        for _, item in ipairs(char:GetChildren()) do
            if item:IsA("Accessory") then
                table.insert(OriginalAvatar.Accessories, item:Clone())
            end
        end
        
        HasBackup = true
    end
    
    -- Get user info
    local function GetUserInfo(input)
        local userId = tonumber(input)
        if userId then
            pcall(function()
                local player = Players:GetPlayerByUserId(userId)
                if player then return player.Name, userId end
            end)
            
            local success, response = pcall(function()
                return game:HttpGet("https://users.roblox.com/v1/users/" .. userId)
            end)
            
            if success then
                local data = HttpService:JSONDecode(response)
                if data and data.name then return data.name, userId end
            end
        else
            local success, response = pcall(function()
                return game:HttpGet("https://api.roblox.com/users/get-by-username?username=" .. input)
            end)
            
            if success then
                local data = HttpService:JSONDecode(response)
                if data and data.Id then return data.Username, data.Id end
            end
        end
        return nil, nil
    end
    
    -- Clone avatar function
    local function CloneAvatar(userId, username)
        if not LocalPlayer.Character then return false end
        if not HasBackup then BackupOriginalAvatar() end
        
        local rootPart = LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
        if rootPart then CreateExplosionEffect(rootPart.Position) end
        
        local success = pcall(function()
            LocalPlayer.CharacterAppearanceId = userId
        end)
        
        if success then
            Services.StarterGui:SetCore("SendNotification", {
                Title = "SUCCESS!",
                Text = "Cloned: " .. (username or "User"),
                Duration = 3,
                Icon = "rbxassetid://6723928012"
            })
            
            task.wait(0.5)
            if LocalPlayer.Character then LocalPlayer.Character:BreakJoints() end
            return true
        end
        return false
    end
    
    -- Reset function
    local function ResetToOriginal()
        if not HasBackup then return end
        LocalPlayer.CharacterAppearanceId = OriginalAvatar.CharacterAppearanceId
        
        if LocalPlayer.Character then
            local char = LocalPlayer.Character
            for _, item in ipairs(char:GetChildren()) do
                if item:IsA("Shirt") or item:IsA("Pants") or item:IsA("ShirtGraphic") or item:IsA("Accessory") then
                    item:Destroy()
                end
            end
            
            task.wait(1)
            if char then
                for _, item in ipairs(OriginalAvatar.Clothing) do item:Clone().Parent = char end
                for _, item in ipairs(OriginalAvatar.Accessories) do item:Clone().Parent = char end
            end
        end
        HasBackup = false
        
        Services.StarterGui:SetCore("SendNotification", {
            Title = "RESET",
            Text = "Avatar restored!",
            Duration = 3
        })
    end

    -- Random Avatar
    local function RandomAvatar()
        local randomId = math.random(1, 50000000)
        CloneAvatar(randomId, "Random User")
    end
    
    -- [[ NEW FUNCTION: Create Floating UI ]] --
    local function CreateFloatingWindow()
        if FloatingFrame then return end
        
        local ScreenGui = UI:GetScreenGui()
        if not ScreenGui then return end
        
        -- Container Frame
        FloatingFrame = Instance.new("Frame")
        FloatingFrame.Name = "CloneFloatingUI"
        FloatingFrame.Size = UDim2.new(0, 200, 0, 140)
        FloatingFrame.Position = UDim2.new(0.5, -100, 0.5, -70) -- Center
        FloatingFrame.BackgroundColor3 = Color3.fromRGB(35, 20, 50)
        FloatingFrame.BorderSizePixel = 0
        FloatingFrame.Visible = false
        FloatingFrame.Parent = ScreenGui
        
        -- Styling
        local corner = Instance.new("UICorner")
        corner.CornerRadius = UDim.new(0, 10)
        corner.Parent = FloatingFrame
        
        local stroke = Instance.new("UIStroke")
        stroke.Color = Color3.fromRGB(160, 32, 240)
        stroke.Thickness = 2
        stroke.Parent = FloatingFrame

        -- Title
        local title = Instance.new("TextLabel")
        title.Size = UDim2.new(1, 0, 0, 25)
        title.BackgroundTransparency = 1
        title.Text = "CLONE MENU"
        title.TextColor3 = Color3.fromRGB(255, 255, 255)
        title.Font = Enum.Font.GothamBold
        title.TextSize = 14
        title.Parent = FloatingFrame

        -- Close Button (X)
        local closeBtn = Instance.new("TextButton")
        closeBtn.Size = UDim2.new(0, 25, 0, 25)
        closeBtn.Position = UDim2.new(1, -25, 0, 0)
        closeBtn.BackgroundTransparency = 1
        closeBtn.Text = "X"
        closeBtn.TextColor3 = Color3.fromRGB(255, 100, 100)
        closeBtn.Font = Enum.Font.GothamBold
        closeBtn.Parent = FloatingFrame
        
        closeBtn.MouseButton1Click:Connect(function()
            FloatingFrame.Visible = false
            MiniMenuActive = false
            -- Reset Mini Menu Logo size
            if MiniMenuLogo then
                TweenService:Create(MiniMenuLogo, TweenInfo.new(0.3), {
                    BackgroundColor3 = Color3.fromRGB(45, 25, 65),
                    Size = UDim2.new(0, 40, 0, 40)
                }):Play()
            end
        end)

        -- Input Box
        local input = Instance.new("TextBox")
        input.Size = UDim2.new(0.9, 0, 0, 30)
        input.Position = UDim2.new(0.05, 0, 0.25, 0)
        input.BackgroundColor3 = Color3.fromRGB(20, 10, 30)
        input.Text = ""
        input.PlaceholderText = "Username / ID"
        input.TextColor3 = Color3.new(1,1,1)
        input.PlaceholderColor3 = Color3.fromRGB(150,150,150)
        input.Font = Enum.Font.Gotham
        input.TextSize = 12
        input.Parent = FloatingFrame
        
        local inCorner = Instance.new("UICorner")
        inCorner.CornerRadius = UDim.new(0, 6)
        inCorner.Parent = input

        -- Clone Button
        local btnClone = Instance.new("TextButton")
        btnClone.Size = UDim2.new(0.42, 0, 0, 30)
        btnClone.Position = UDim2.new(0.05, 0, 0.55, 0)
        btnClone.BackgroundColor3 = Color3.fromRGB(40, 150, 40)
        btnClone.Text = "COPY"
        btnClone.TextColor3 = Color3.new(1,1,1)
        btnClone.Font = Enum.Font.GothamBold
        btnClone.TextSize = 12
        btnClone.Parent = FloatingFrame
        
        local bCorner = Instance.new("UICorner")
        bCorner.CornerRadius = UDim.new(0, 6)
        bCorner.Parent = btnClone

        -- Reset Button
        local btnReset = Instance.new("TextButton")
        btnReset.Size = UDim2.new(0.42, 0, 0, 30)
        btnReset.Position = UDim2.new(0.53, 0, 0.55, 0)
        btnReset.BackgroundColor3 = Color3.fromRGB(150, 40, 40)
        btnReset.Text = "RESET"
        btnReset.TextColor3 = Color3.new(1,1,1)
        btnReset.Font = Enum.Font.GothamBold
        btnReset.TextSize = 12
        btnReset.Parent = FloatingFrame

        local rCorner = Instance.new("UICorner")
        rCorner.CornerRadius = UDim.new(0, 6)
        rCorner.Parent = btnReset
        
        -- Random Button (Bottom)
        local btnRand = Instance.new("TextButton")
        btnRand.Size = UDim2.new(0.9, 0, 0, 25)
        btnRand.Position = UDim2.new(0.05, 0, 0.8, 0)
        btnRand.BackgroundColor3 = Color3.fromRGB(60, 40, 90)
        btnRand.Text = "RANDOM AVATAR"
        btnRand.TextColor3 = Color3.new(1,1,1)
        btnRand.Font = Enum.Font.Gotham
        btnRand.TextSize = 10
        btnRand.Parent = FloatingFrame
        
        local randCorner = Instance.new("UICorner")
        randCorner.CornerRadius = UDim.new(0, 6)
        randCorner.Parent = btnRand

        -- Functionality
        btnClone.MouseButton1Click:Connect(function()
            local txt = input.Text
            if txt == "" then return end
            local name, id = GetUserInfo(txt)
            if id then CloneAvatar(id, name) end
        end)

        btnReset.MouseButton1Click:Connect(function() ResetToOriginal() end)
        btnRand.MouseButton1Click:Connect(function() RandomAvatar() end)

        -- Make Draggable
        local dragging, dragInput, dragStart, startPos
        FloatingFrame.InputBegan:Connect(function(inp)
            if inp.UserInputType == Enum.UserInputType.MouseButton1 or inp.UserInputType == Enum.UserInputType.Touch then
                dragging = true
                dragStart = inp.Position
                startPos = FloatingFrame.Position
                inp.Changed:Connect(function()
                    if inp.UserInputState == Enum.UserInputState.End then dragging = false end
                end)
            end
        end)
        FloatingFrame.InputChanged:Connect(function(inp)
            if dragging and (inp.UserInputType == Enum.UserInputType.MouseMovement or inp.UserInputType == Enum.UserInputType.Touch) then
                local delta = inp.Position - dragStart
                FloatingFrame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
            end
        end)
    end
    
    -- Create mini menu logo
    local function CreateMiniMenuLogo()
        if MiniMenuLogo then return end
        
        local ScreenGui = UI:GetScreenGui()
        if not ScreenGui then return end
        
        MiniMenuLogo = Instance.new("ImageButton")
        MiniMenuLogo.Name = "CloneAvatarMiniMenu"
        MiniMenuLogo.Size = UDim2.new(0, 40, 0, 40)
        MiniMenuLogo.Position = UDim2.new(0.92, 0, 0.15, 0)
        MiniMenuLogo.BackgroundColor3 = Color3.fromRGB(45, 25, 65)
        MiniMenuLogo.Image = "rbxassetid://10734996854"
        MiniMenuLogo.ImageColor3 = Color3.fromRGB(160, 32, 240)
        
        local corner = Instance.new("UICorner")
        corner.CornerRadius = UDim.new(1, 0)
        corner.Parent = MiniMenuLogo
        
        local stroke = Instance.new("UIStroke")
        stroke.Color = Color3.fromRGB(200, 100, 255)
        stroke.Thickness = 2
        stroke.Parent = MiniMenuLogo
        
        MiniMenuLogo.Parent = ScreenGui
        
        -- Create the UI frame but keep hidden
        CreateFloatingWindow()
        
        -- Click handler (FIXED LOGIC)
        MiniMenuLogo.MouseButton1Click:Connect(function()
            MiniMenuActive = not MiniMenuActive
            
            -- Ensure floating frame exists
            if not FloatingFrame then CreateFloatingWindow() end
            
            if MiniMenuActive then
                -- Show Menu
                FloatingFrame.Visible = true
                TweenService:Create(MiniMenuLogo, TweenInfo.new(0.3), {
                    BackgroundColor3 = Color3.fromRGB(80, 40, 120),
                    Size = UDim2.new(0, 45, 0, 45)
                }):Play()
            else
                -- Hide Menu
                FloatingFrame.Visible = false
                TweenService:Create(MiniMenuLogo, TweenInfo.new(0.3), {
                    BackgroundColor3 = Color3.fromRGB(45, 25, 65),
                    Size = UDim2.new(0, 40, 0, 40)
                }):Play()
            end
        end)
        
        -- Draggable Logo
        local dragging = false
        local dragStart, startPos
        MiniMenuLogo.InputBegan:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
                dragging = true
                dragStart = input.Position
                startPos = MiniMenuLogo.Position
                input.Changed:Connect(function()
                    if input.UserInputState == Enum.UserInputState.End then dragging = false end
                end)
            end
        end)
        Services.UserInputService.InputChanged:Connect(function(input)
            if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
                local delta = input.Position - dragStart
                MiniMenuLogo.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
            end
        end)
    end
    
    local function RemoveMiniMenuLogo()
        if MiniMenuLogo then MiniMenuLogo:Destroy(); MiniMenuLogo = nil end
        if FloatingFrame then FloatingFrame:Destroy(); FloatingFrame = nil end
        MiniMenuActive = false
    end
    
    -- Main UI Creation (Tab in Executor)
    local function CreateUI()
        local tab = UI:Tab("Cosmetics")
        tab:Label("COPY AVATAR V2.1")
        tab:Label("Fixed by Gemini")
        
        -- Input Area
        tab:Label("─ CHANGER ─")
        local inputFrame = Instance.new("Frame")
        inputFrame.Size = UDim2.new(1, -10, 0, 30)
        inputFrame.BackgroundColor3 = Color3.fromRGB(30, 20, 40)
        inputFrame.Parent = tab.Content
        
        local corner = Instance.new("UICorner")
        corner.CornerRadius = UDim.new(0, 6)
        corner.Parent = inputFrame
        
        local textBox = Instance.new("TextBox")
        textBox.Size = UDim2.new(0.9, 0, 0.8, 0)
        textBox.Position = UDim2.new(0.05, 0, 0.1, 0)
        textBox.BackgroundTransparency = 1
        textBox.Text = ""
        textBox.PlaceholderText = "Enter Username or User ID..."
        textBox.PlaceholderColor3 = Color3.fromRGB(150, 150, 150)
        textBox.TextColor3 = Color3.new(1, 1, 1)
        textBox.Parent = inputFrame
        
        -- Buttons
        local buttonContainer = Instance.new("Frame")
        buttonContainer.Size = UDim2.new(1, 0, 0, 30)
        buttonContainer.BackgroundTransparency = 1
        buttonContainer.Parent = tab.Content
        local layout = Instance.new("UIListLayout")
        layout.FillDirection = Enum.FillDirection.Horizontal
        layout.HorizontalAlignment = Enum.HorizontalAlignment.Center
        layout.Padding = UDim.new(0, 10)
        layout.Parent = buttonContainer
        
        local copyBtn = Instance.new("TextButton")
        copyBtn.Size = UDim2.new(0.4, 0, 0, 26)
        copyBtn.BackgroundColor3 = Color3.fromRGB(40, 150, 40)
        copyBtn.Text = "✅ COPY"
        copyBtn.TextColor3 = Color3.new(1,1,1)
        copyBtn.Parent = buttonContainer
        Instance.new("UICorner", copyBtn).CornerRadius = UDim.new(0,6)
        
        local randomBtn = Instance.new("TextButton")
        randomBtn.Size = UDim2.new(0.4, 0, 0, 26)
        randomBtn.BackgroundColor3 = Color3.fromRGB(150, 40, 40)
        randomBtn.Text = "❌ RANDOM"
        randomBtn.TextColor3 = Color3.new(1,1,1)
        randomBtn.Parent = buttonContainer
        Instance.new("UICorner", randomBtn).CornerRadius = UDim.new(0,6)
        
        -- Handlers
        copyBtn.MouseButton1Click:Connect(function()
            local u, i = GetUserInfo(textBox.Text)
            if i then CloneAvatar(i, u) end
        end)
        randomBtn.MouseButton1Click:Connect(function() RandomAvatar() end)
        
        -- Favorites Section (Simplified for brevity)
        tab:Label("─ EXTRAS ─")
        local resetBtn = Instance.new("TextButton")
        resetBtn.Size = UDim2.new(1, -10, 0, 26)
        resetBtn.BackgroundColor3 = Color3.fromRGB(150, 40, 40)
        resetBtn.Text = "✖ RESET TO ORIGINAL"
        resetBtn.TextColor3 = Color3.new(1,1,1)
        resetBtn.Parent = tab.Content
        Instance.new("UICorner", resetBtn).CornerRadius = UDim.new(0,6)
        resetBtn.MouseButton1Click:Connect(ResetToOriginal)
        
        -- Mini Menu Toggle
        local miniMenuToggle = tab:Toggle("Activate Mini Menu Logo", function(state)
            if state then
                CreateMiniMenuLogo()
            else
                RemoveMiniMenuLogo()
            end
        end)
        
        -- Load
        LoadFavorites()
        spawn(function() task.wait(2); if not HasBackup then BackupOriginalAvatar() end end)
    end
    
    CreateUI()
    
    return {
        CloneAvatar = CloneAvatar,
        CreateMiniMenuLogo = CreateMiniMenuLogo
    }
end