-- cloneAvatar.lua
-- Fitur Clone Avatar untuk Vanzyxxx Modular
-- Author: Generated by AI
-- Version: 2.0.0
-- Delta Executor Compatible

return function(UI, Services, Config, Theme)
    local Players = Services.Players
    local LocalPlayer = Players.LocalPlayer
    local HttpService = Services.HttpService
    local MarketplaceService = Services.MarketplaceService
    local RunService = Services.RunService
    local TweenService = Services.TweenService
    
    -- Favorites storage
    local FAVORITES_FILE = "Vanzyxxx_Favorites.json"
    local MAX_FAVORITES = 20
    
    -- Default favorites jika file tidak ada
    local DEFAULT_FAVORITES = {
        {name = "panggiljee", id = 9298294077},
        {name = "icibos0325", id = 9101145665},
        {name = "imyulay", id = 4401600759}
    }
    
    -- Current favorites
    local FavoritesList = {}
    
    -- Original avatar backup
    local OriginalAvatar = {}
    local HasBackup = false
    
    -- Mini menu logo state
    local MiniMenuLogo = nil
    local MiniMenuActive = false
    
    -- Effects
    local ExplosionEffect = nil
    
    -- Load favorites from file
    local function LoadFavorites()
        if isfile and isfile(FAVORITES_FILE) then
            local success, data = pcall(function()
                return HttpService:JSONDecode(readfile(FAVORITES_FILE))
            end)
            if success and type(data) == "table" then
                FavoritesList = data
                return
            end
        end
        FavoritesList = DEFAULT_FAVORITES
    end
    
    -- Save favorites to file
    local function SaveFavorites()
        if writefile then
            pcall(function()
                writefile(FAVORITES_FILE, HttpService:JSONEncode(FavoritesList))
            end)
        end
    end
    
    -- Add user to favorites
    local function AddToFavorites(username, userId)
        -- Check if already in favorites
        for _, fav in ipairs(FavoritesList) do
            if fav.id == userId then
                Services.StarterGui:SetCore("SendNotification", {
                    Title = "Favorites",
                    Text = username .. " already in favorites!",
                    Duration = 3
                })
                return false
            end
        end
        
        -- Check limit
        if #FavoritesList >= MAX_FAVORITES then
            Services.StarterGui:SetCore("SendNotification", {
                Title = "Favorites",
                Text = "Max favorites reached (" .. MAX_FAVORITES .. ")",
                Duration = 3
            })
            return false
        end
        
        -- Add to list
        table.insert(FavoritesList, {name = username, id = userId})
        SaveFavorites()
        
        Services.StarterGui:SetCore("SendNotification", {
            Title = "Favorites",
            Text = "Added " .. username .. " to favorites!",
            Duration = 3
        })
        
        return true
    end
    
    -- Remove from favorites
    local function RemoveFavorite(userId)
        for i, fav in ipairs(FavoritesList) do
            if fav.id == userId then
                table.remove(FavoritesList, i)
                SaveFavorites()
                return true
            end
        end
        return false
    end
    
    -- Create explosion effect
    local function CreateExplosionEffect(position)
        if ExplosionEffect then
            ExplosionEffect:Destroy()
        end
        
        ExplosionEffect = Instance.new("Part")
        ExplosionEffect.Name = "AvatarCloneExplosion"
        ExplosionEffect.Size = Vector3.new(1, 1, 1)
        ExplosionEffect.Position = position
        ExplosionEffect.Anchored = true
        ExplosionEffect.CanCollide = false
        ExplosionEffect.Transparency = 1
        ExplosionEffect.Parent = Services.Workspace
        
        -- Fire particles
        local fire = Instance.new("Fire")
        fire.Size = 10
        fire.Heat = 15
        fire.Color = Color3.fromRGB(255, 100, 0)
        fire.SecondaryColor = Color3.fromRGB(255, 200, 0)
        fire.Parent = ExplosionEffect
        
        -- Light
        local light = Instance.new("PointLight")
        light.Brightness = 5
        light.Range = 20
        light.Color = Color3.fromRGB(255, 150, 0)
        light.Parent = ExplosionEffect
        
        -- Sound
        local sound = Instance.new("Sound")
        sound.SoundId = "rbxassetid://138080902"
        sound.Volume = 0.5
        sound.Parent = ExplosionEffect
        sound:Play()
        
        -- Tween effects
        TweenService:Create(fire, TweenInfo.new(1.5), {Size = 0}):Play()
        TweenService:Create(light, TweenInfo.new(1.5), {Brightness = 0}):Play()
        
        -- Cleanup
        game:GetService("Debris"):AddItem(ExplosionEffect, 2)
    end
    
    -- Backup original avatar
    local function BackupOriginalAvatar()
        if HasBackup or not LocalPlayer.Character then return end
        
        local char = LocalPlayer.Character
        OriginalAvatar = {
            CharacterAppearanceId = LocalPlayer.CharacterAppearanceId,
            BodyColors = LocalPlayer:GetBodyColors()
        }
        
        -- Save clothing items
        OriginalAvatar.Clothing = {}
        for _, item in ipairs(char:GetChildren()) do
            if item:IsA("Shirt") or item:IsA("Pants") or item:IsA("ShirtGraphic") then
                table.insert(OriginalAvatar.Clothing, item:Clone())
            end
        end
        
        -- Save accessories
        OriginalAvatar.Accessories = {}
        for _, item in ipairs(char:GetChildren()) do
            if item:IsA("Accessory") then
                table.insert(OriginalAvatar.Accessories, item:Clone())
            end
        end
        
        HasBackup = true
    end
    
    -- Get user info from input
    local function GetUserInfo(input)
        -- Check if input is numeric (User ID)
        local userId = tonumber(input)
        if userId then
            -- It's a numeric ID
            pcall(function()
                local player = Players:GetPlayerByUserId(userId)
                if player then
                    return player.Name, userId
                end
            end)
            
            -- Try to get username from API
            local success, response = pcall(function()
                return game:HttpGet("https://users.roblox.com/v1/users/" .. userId)
            end)
            
            if success then
                local data = HttpService:JSONDecode(response)
                if data and data.name then
                    return data.name, userId
                end
            end
        else
            -- It's a username
            local success, response = pcall(function()
                return game:HttpGet("https://api.roblox.com/users/get-by-username?username=" .. input)
            end)
            
            if success then
                local data = HttpService:JSONDecode(response)
                if data and data.Id then
                    return data.Username, data.Id
                end
            end
        end
        
        return nil, nil
    end
    
    -- Clone avatar function with explosion effect
    local function CloneAvatar(userId, username)
        if not LocalPlayer.Character then
            Services.StarterGui:SetCore("SendNotification", {
                Title = "Error",
                Text = "No character found!",
                Duration = 3
            })
            return false
        end
        
        -- Backup original if not done
        if not HasBackup then
            BackupOriginalAvatar()
        end
        
        -- Create explosion effect at character position
        local rootPart = LocalPlayer.Character:FindFirstChild("HumanoidRootPart")
        if rootPart then
            CreateExplosionEffect(rootPart.Position)
        end
        
        -- Load character appearance
        local success = pcall(function()
            LocalPlayer.CharacterAppearanceId = userId
        end)
        
        if success then
            Services.StarterGui:SetCore("SendNotification", {
                Title = "SUCCESS!",
                Text = "Avatar cloned from " .. (username or "User") .. "!",
                Duration = 4,
                Icon = "rbxassetid://6723928012"
            })
            
            -- Wait a bit then respawn to apply changes
            task.wait(0.5)
            if LocalPlayer.Character then
                LocalPlayer.Character:BreakJoints()
            end
            
            return true
        else
            Services.StarterGui:SetCore("SendNotification", {
                Title = "ERROR",
                Text = "Failed to clone avatar!",
                Duration = 3
            })
            return false
        end
    end
    
    -- Reset to original avatar
    local function ResetToOriginal()
        if not HasBackup then
            Services.StarterGui:SetCore("SendNotification", {
                Title = "Info",
                Text = "No backup found!",
                Duration = 3
            })
            return
        end
        
        -- Apply original appearance
        LocalPlayer.CharacterAppearanceId = OriginalAvatar.CharacterAppearanceId
        
        -- Re-add original clothing and accessories
        if LocalPlayer.Character then
            local char = LocalPlayer.Character
            
            -- Remove current clothing
            for _, item in ipairs(char:GetChildren()) do
                if item:IsA("Shirt") or item:IsA("Pants") or item:IsA("ShirtGraphic") or item:IsA("Accessory") then
                    item:Destroy()
                end
            end
            
            -- Add back original items
            task.wait(1) -- Wait for character to load
            
            if char then
                for _, item in ipairs(OriginalAvatar.Clothing) do
                    local clone = item:Clone()
                    clone.Parent = char
                end
                
                for _, accessory in ipairs(OriginalAvatar.Accessories) do
                    local clone = accessory:Clone()
                    clone.Parent = char
                end
            end
        end
        
        Services.StarterGui:SetCore("SendNotification", {
            Title = "RESET",
            Text = "Avatar restored to original!",
            Duration = 3
        })
        
        HasBackup = false
    end
    
    -- Random avatar
    local function RandomAvatar()
        -- Generate random user ID (within valid range)
        local randomId = math.random(1, 50000000)
        CloneAvatar(randomId, "Random User")
    end
    
    -- Create mini menu logo
    local function CreateMiniMenuLogo()
        if MiniMenuLogo then return end
        
        local ScreenGui = UI:GetScreenGui()
        if not ScreenGui then return end
        
        MiniMenuLogo = Instance.new("ImageButton")
        MiniMenuLogo.Name = "CloneAvatarMiniMenu"
        MiniMenuLogo.Size = UDim2.new(0, 40, 0, 40)
        MiniMenuLogo.Position = UDim2.new(0.92, 0, 0.15, 0)
        MiniMenuLogo.BackgroundColor3 = Color3.fromRGB(45, 25, 65)
        MiniMenuLogo.Image = "rbxassetid://10734996854" -- 👥 icon
        MiniMenuLogo.ImageColor3 = Color3.fromRGB(160, 32, 240) -- Ungu
        
        local corner = Instance.new("UICorner")
        corner.CornerRadius = UDim.new(1, 0)
        corner.Parent = MiniMenuLogo
        
        local stroke = Instance.new("UIStroke")
        stroke.Color = Color3.fromRGB(200, 100, 255)
        stroke.Thickness = 2
        stroke.Parent = MiniMenuLogo
        
        MiniMenuLogo.Parent = ScreenGui
        
        -- Click handler
        MiniMenuLogo.MouseButton1Click:Connect(function()
            MiniMenuActive = not MiniMenuActive
            if MiniMenuActive then
                TweenService:Create(MiniMenuLogo, TweenInfo.new(0.3), {
                    BackgroundColor3 = Color3.fromRGB(80, 40, 120),
                    Size = UDim2.new(0, 45, 0, 45)
                }):Play()
                
                Services.StarterGui:SetCore("SendNotification", {
                    Title = "Clone Avatar",
                    Text = "Mini Menu Activated!",
                    Duration = 2
                })
            else
                TweenService:Create(MiniMenuLogo, TweenInfo.new(0.3), {
                    BackgroundColor3 = Color3.fromRGB(45, 25, 65),
                    Size = UDim2.new(0, 40, 0, 40)
                }):Play()
            end
        end)
        
        -- Draggable
        local dragging = false
        local dragStart, startPos
        
        MiniMenuLogo.InputBegan:Connect(function(input)
            if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
                dragging = true
                dragStart = input.Position
                startPos = MiniMenuLogo.Position
                
                input.Changed:Connect(function()
                    if input.UserInputState == Enum.UserInputState.End then
                        dragging = false
                    end
                end)
            end
        end)
        
        Services.UserInputService.InputChanged:Connect(function(input)
            if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch) then
                local delta = input.Position - dragStart
                MiniMenuLogo.Position = UDim2.new(
                    startPos.X.Scale,
                    startPos.X.Offset + delta.X,
                    startPos.Y.Scale,
                    startPos.Y.Offset + delta.Y
                )
            end
        end)
    end
    
    -- Remove mini menu logo
    local function RemoveMiniMenuLogo()
        if MiniMenuLogo then
            MiniMenuLogo:Destroy()
            MiniMenuLogo = nil
            MiniMenuActive = false
        end
    end
    
    -- Create the UI
    local function CreateUI()
        local tab = UI:Tab("Cosmetics")
        
        -- Title
        tab:Label("COPY AVATAR")
        tab:Label("by FayintXCode")
        
        -- Section: CHANGER
        tab:Label("─ CHANGER ─")
        
        -- Input field
        local inputFrame = Instance.new("Frame")
        inputFrame.Size = UDim2.new(1, -10, 0, 30)
        inputFrame.BackgroundColor3 = Color3.fromRGB(30, 20, 40)
        inputFrame.Parent = tab.Content
        
        local corner = Instance.new("UICorner")
        corner.CornerRadius = UDim.new(0, 6)
        corner.Parent = inputFrame
        
        local textBox = Instance.new("TextBox")
        textBox.Size = UDim2.new(0.9, 0, 0.8, 0)
        textBox.Position = UDim2.new(0.05, 0, 0.1, 0)
        textBox.BackgroundTransparency = 1
        textBox.Text = ""
        textBox.PlaceholderText = "Enter Username or User ID..."
        textBox.PlaceholderColor3 = Color3.fromRGB(150, 150, 150)
        textBox.TextColor3 = Color3.new(1, 1, 1)
        textBox.Font = Enum.Font.Gotham
        textBox.TextSize = 12
        textBox.Parent = inputFrame
        
        -- Action buttons container
        local buttonContainer = Instance.new("Frame")
        buttonContainer.Size = UDim2.new(1, 0, 0, 30)
        buttonContainer.BackgroundTransparency = 1
        buttonContainer.Parent = tab.Content
        
        local layout = Instance.new("UIListLayout")
        layout.FillDirection = Enum.FillDirection.Horizontal
        layout.HorizontalAlignment = Enum.HorizontalAlignment.Center
        layout.Padding = UDim.new(0, 10)
        layout.Parent = buttonContainer
        
        -- Copy button
        local copyBtn = Instance.new("TextButton")
        copyBtn.Size = UDim2.new(0.4, 0, 0, 26)
        copyBtn.BackgroundColor3 = Color3.fromRGB(40, 150, 40)
        copyBtn.Text = "✅ COPY"
        copyBtn.TextColor3 = Color3.new(1, 1, 1)
        copyBtn.Font = Enum.Font.GothamBold
        copyBtn.TextSize = 12
        copyBtn.Parent = buttonContainer
        
        local copyCorner = Instance.new("UICorner")
        copyCorner.CornerRadius = UDim.new(0, 6)
        copyCorner.Parent = copyBtn
        
        -- Random button
        local randomBtn = Instance.new("TextButton")
        randomBtn.Size = UDim2.new(0.4, 0, 0, 26)
        randomBtn.BackgroundColor3 = Color3.fromRGB(150, 40, 40)
        randomBtn.Text = "❌ RANDOM"
        randomBtn.TextColor3 = Color3.new(1, 1, 1)
        randomBtn.Font = Enum.Font.GothamBold
        randomBtn.TextSize = 12
        randomBtn.Parent = buttonContainer
        
        local randomCorner = Instance.new("UICorner")
        randomCorner.CornerRadius = UDim.new(0, 6)
        randomCorner.Parent = randomBtn
        
        -- Section: FAVORITED
        tab:Label("─ FAVORITED ─")
        
        -- Favorites list container
        local favoritesContainer = Instance.new("ScrollingFrame")
        favoritesContainer.Size = UDim2.new(1, 0, 0, 120)
        favoritesContainer.BackgroundColor3 = Color3.fromRGB(25, 15, 35)
        favoritesContainer.ScrollBarThickness = 2
        favoritesContainer.AutomaticCanvasSize = Enum.AutomaticSize.Y
        favoritesContainer.Parent = tab.Content
        
        local favCorner = Instance.new("UICorner")
        favCorner.CornerRadius = UDim.new(0, 6)
        favCorner.Parent = favoritesContainer
        
        local favLayout = Instance.new("UIListLayout")
        favLayout.Padding = UDim.new(0, 5)
        favLayout.Parent = favoritesContainer
        
        -- Function to refresh favorites list
        local function RefreshFavoritesList()
            for _, child in ipairs(favoritesContainer:GetChildren()) do
                if child:IsA("Frame") then
                    child:Destroy()
                end
            end
            
            for _, fav in ipairs(FavoritesList) do
                local favFrame = Instance.new("Frame")
                favFrame.Size = UDim2.new(1, -10, 0, 40)
                favFrame.BackgroundColor3 = Color3.fromRGB(40, 25, 55)
                favFrame.Parent = favoritesContainer
                
                local favCorner = Instance.new("UICorner")
                favCorner.CornerRadius = UDim.new(0, 6)
                favCorner.Parent = favFrame
                
                local nameLabel = Instance.new("TextLabel")
                nameLabel.Size = UDim2.new(0.7, 0, 0.5, 0)
                nameLabel.Position = UDim2.new(0.05, 0, 0.1, 0)
                nameLabel.BackgroundTransparency = 1
                nameLabel.Text = fav.name
                nameLabel.TextColor3 = Color3.new(1, 1, 1)
                nameLabel.Font = Enum.Font.GothamBold
                nameLabel.TextSize = 12
                nameLabel.TextXAlignment = Enum.TextXAlignment.Left
                nameLabel.Parent = favFrame
                
                local idLabel = Instance.new("TextLabel")
                idLabel.Size = UDim2.new(0.7, 0, 0.5, 0)
                idLabel.Position = UDim2.new(0.05, 0, 0.5, 0)
                idLabel.BackgroundTransparency = 1
                idLabel.Text = "ID: " .. tostring(fav.id)
                idLabel.TextColor3 = Color3.fromRGB(200, 200, 200)
                idLabel.Font = Enum.Font.Gotham
                idLabel.TextSize = 10
                idLabel.TextXAlignment = Enum.TextXAlignment.Left
                idLabel.Parent = favFrame
                
                -- Use button
                local useBtn = Instance.new("TextButton")
                useBtn.Size = UDim2.new(0.2, 0, 0.6, 0)
                useBtn.Position = UDim2.new(0.75, 0, 0.2, 0)
                useBtn.BackgroundColor3 = Color3.fromRGB(60, 40, 100)
                useBtn.Text = "USE"
                useBtn.TextColor3 = Color3.new(1, 1, 1)
                useBtn.Font = Enum.Font.Gotham
                useBtn.TextSize = 10
                useBtn.Parent = favFrame
                
                local useCorner = Instance.new("UICorner")
                useCorner.CornerRadius = UDim.new(0, 4)
                useCorner.Parent = useBtn
                
                -- Use button click
                useBtn.MouseButton1Click:Connect(function()
                    CloneAvatar(fav.id, fav.name)
                end)
            end
        end
        
        -- Action buttons 2
        tab:Label("")
        
        local actionContainer = Instance.new("Frame")
        actionContainer.Size = UDim2.new(1, 0, 0, 60)
        actionContainer.BackgroundTransparency = 1
        actionContainer.Parent = tab.Content
        
        local actionLayout = Instance.new("UIListLayout")
        actionLayout.FillDirection = Enum.FillDirection.Horizontal
        actionLayout.HorizontalAlignment = Enum.HorizontalAlignment.Center
        actionLayout.Padding = UDim.new(0, 10)
        actionLayout.Parent = actionContainer
        
        -- Add to favorites button
        local addFavBtn = Instance.new("TextButton")
        addFavBtn.Size = UDim2.new(0.45, 0, 0, 26)
        addFavBtn.BackgroundColor3 = Color3.fromRGB(200, 150, 30)
        addFavBtn.Text = "★ ADD TO FAVORITES"
        addFavBtn.TextColor3 = Color3.new(1, 1, 1)
        addFavBtn.Font = Enum.Font.GothamBold
        addFavBtn.TextSize = 10
        addFavBtn.Parent = actionContainer
        
        local addCorner = Instance.new("UICorner")
        addCorner.CornerRadius = UDim.new(0, 6)
        addCorner.Parent = addFavBtn
        
        -- Reset button
        local resetBtn = Instance.new("TextButton")
        resetBtn.Size = UDim2.new(0.45, 0, 0, 26)
        resetBtn.BackgroundColor3 = Color3.fromRGB(150, 40, 40)
        resetBtn.Text = "✖ RESET TO ORIGINAL"
        resetBtn.TextColor3 = Color3.new(1, 1, 1)
        resetBtn.Font = Enum.Font.GothamBold
        resetBtn.TextSize = 10
        resetBtn.Parent = actionContainer
        
        local resetCorner = Instance.new("UICorner")
        resetCorner.CornerRadius = UDim.new(0, 6)
        resetCorner.Parent = resetBtn
        
        -- Footer
        tab:Label("")
        tab:Label("Join our Discord!")
        
        local discordBtn = Instance.new("TextButton")
        discordBtn.Size = UDim2.new(1, -10, 0, 26)
        discordBtn.BackgroundColor3 = Color3.fromRGB(88, 101, 242) -- Discord color
        discordBtn.Text = "https://discord.gg/JnUtNJWmjW"
        discordBtn.TextColor3 = Color3.new(1, 1, 1)
        discordBtn.Font = Enum.Font.Gotham
        discordBtn.TextSize = 11
        discordBtn.Parent = tab.Content
        
        local discordCorner = Instance.new("UICorner")
        discordCorner.CornerRadius = UDim.new(0, 6)
        discordCorner.Parent = discordBtn
        
        local copyLinkBtn = Instance.new("TextButton")
        copyLinkBtn.Size = UDim2.new(1, -10, 0, 24)
        copyLinkBtn.BackgroundColor3 = Color3.fromRGB(60, 40, 90)
        copyLinkBtn.Text = "Copy Link"
        copyLinkBtn.TextColor3 = Color3.new(1, 1, 1)
        copyLinkBtn.Font = Enum.Font.Gotham
        copyLinkBtn.TextSize = 11
        copyLinkBtn.Parent = tab.Content
        
        local copyLinkCorner = Instance.new("UICorner")
        copyLinkCorner.CornerRadius = UDim.new(0, 6)
        copyLinkCorner.Parent = copyLinkBtn
        
        -- Mini Menu Toggle
        local miniMenuToggle = tab:Toggle("Activate Mini Menu Logo", function(state)
            if state then
                CreateMiniMenuLogo()
                Services.StarterGui:SetCore("SendNotification", {
                    Title = "Mini Menu",
                    Text = "Mini menu logo created!",
                    Duration = 3
                })
            else
                RemoveMiniMenuLogo()
            end
        end)
        
        -- Button click handlers
        copyBtn.MouseButton1Click:Connect(function()
            local input = textBox.Text
            if input == "" then
                Services.StarterGui:SetCore("SendNotification", {
                    Title = "Error",
                    Text = "Please enter username or ID!",
                    Duration = 3
                })
                return
            end
            
            local username, userId = GetUserInfo(input)
            if username and userId then
                CloneAvatar(userId, username)
            else
                Services.StarterGui:SetCore("SendNotification", {
                    Title = "Error",
                    Text = "User not found!",
                    Duration = 3
                })
            end
        end)
        
        randomBtn.MouseButton1Click:Connect(function()
            RandomAvatar()
        end)
        
        addFavBtn.MouseButton1Click:Connect(function()
            local input = textBox.Text
            if input == "" then
                Services.StarterGui:SetCore("SendNotification", {
                    Title = "Error",
                    Text = "Enter username/ID first!",
                    Duration = 3
                })
                return
            end
            
            local username, userId = GetUserInfo(input)
            if username and userId then
                if AddToFavorites(username, userId) then
                    RefreshFavoritesList()
                end
            else
                Services.StarterGui:SetCore("SendNotification", {
                    Title = "Error",
                    Text = "Cannot add invalid user!",
                    Duration = 3
                })
            end
        end)
        
        resetBtn.MouseButton1Click:Connect(function()
            ResetToOriginal()
        end)
        
        discordBtn.MouseButton1Click:Connect(function()
            pcall(function()
                setclipboard("https://discord.gg/JnUtNJWmjW")
            end)
            
            Services.StarterGui:SetCore("SendNotification", {
                Title = "Discord",
                Text = "Link copied to clipboard!",
                Duration = 3
            })
        end)
        
        copyLinkBtn.MouseButton1Click:Connect(function()
            pcall(function()
                setclipboard("https://discord.gg/JnUtNJWmjW")
            end)
            
            Services.StarterGui:SetCore("SendNotification", {
                Title = "Copied!",
                Text = "Discord link copied!",
                Duration = 2
            })
        end)
        
        -- Initialize
        LoadFavorites()
        RefreshFavoritesList()
        
        -- Backup original on first load
        spawn(function()
            task.wait(2)
            if not HasBackup then
                BackupOriginalAvatar()
            end
        end)
    end
    
    -- Initialize
    CreateUI()
    
    Services.StarterGui:SetCore("SendNotification", {
        Title = "Clone Avatar",
        Text = "Loaded successfully!",
        Duration = 3
    })
    
    -- Return module for external access
    return {
        CloneAvatar = CloneAvatar,
        ResetToOriginal = ResetToOriginal,
        RandomAvatar = RandomAvatar,
        AddToFavorites = AddToFavorites,
        RemoveFavorite = RemoveFavorite,
        CreateMiniMenuLogo = CreateMiniMenuLogo,
        RemoveMiniMenuLogo = RemoveMiniMenuLogo
    }
end