-- features/Visual/cloneAvatar.lua
-- Fitur Clone Avatar untuk Vanzyxxx Modular
-- Author: FayintXCode (Generated by Gemini)
-- Version: 1.0.0
-- Delta Executor Compatible

return function(UI, Services, Config, Theme)
    -- [[ SERVICES ]]
    local Players = Services.Players
    local UserInputService = Services.UserInputService
    local HttpService = Services.HttpService
    local StarterGui = Services.StarterGui
    local TweenService = Services.TweenService
    
    local LocalPlayer = Players.LocalPlayer
    
    -- [[ CONFIGURATION & STATE ]]
    local CloneConfig = {
        FileName = "VanzyAvatarFavorites.json",
        Theme = {
            Background = Color3.fromRGB(15, 15, 15),
            ItemBG = Color3.fromRGB(25, 25, 25),
            Accent = Color3.fromRGB(255, 40, 70), -- Merah Pink sesuai gambar
            Text = Color3.fromRGB(255, 255, 255),
            SubText = Color3.fromRGB(150, 150, 150),
            Success = Color3.fromRGB(46, 204, 113),
            Random = Color3.fromRGB(200, 40, 60)
        }
    }
    
    local State = {
        OriginalDescription = nil,
        Favorites = {}
    }

    -- [[ FILE SYSTEM MANAGER ]]
    local function LoadFavorites()
        if isfile and isfile(CloneConfig.FileName) then
            local success, result = pcall(function()
                return HttpService:JSONDecode(readfile(CloneConfig.FileName))
            end)
            if success and type(result) == "table" then
                State.Favorites = result
            end
        end
    end

    local function SaveFavorites()
        if writefile then
            local json = HttpService:JSONEncode(State.Favorites)
            writefile(CloneConfig.FileName, json)
        end
    end
    
    -- Load initial data
    LoadFavorites()

    -- [[ CORE LOGIC ]]
    
    -- Simpan penampilan asli saat script dimuat pertama kali
    pcall(function()
        if LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("Humanoid") then
            State.OriginalDescription = LocalPlayer.Character.Humanoid:GetAppliedDescription()
        end
    end)

    local function Notify(title, text)
        StarterGui:SetCore("SendNotification", {
            Title = title,
            Text = text,
            Duration = 3
        })
    end

    local function ApplyAvatar(userId)
        userId = tonumber(userId)
        if not userId then return end

        task.spawn(function()
            local character = LocalPlayer.Character
            local humanoid = character and character:FindFirstChild("Humanoid")
            
            if not humanoid then return end

            -- Simpan original jika belum ada
            if not State.OriginalDescription then
                State.OriginalDescription = humanoid:GetAppliedDescription()
            end

            Notify("Clone Avatar", "Fetching assets...")

            local success, desc = pcall(function()
                return Players:GetHumanoidDescriptionFromUserId(userId)
            end)

            if success and desc then
                humanoid:ApplyDescription(desc)
                Notify("Success", "Avatar cloned successfully!")
            else
                Notify("Error", "Failed to load avatar. ID invalid?")
            end
        end)
    end

    local function ResetAvatar()
        if State.OriginalDescription and LocalPlayer.Character then
            local hum = LocalPlayer.Character:FindFirstChild("Humanoid")
            if hum then
                hum:ApplyDescription(State.OriginalDescription)
                Notify("Reset", "Avatar restored to original.")
            end
        else
            Notify("Error", "No original avatar saved.")
        end
    end

    local function GetIdFromInput(input)
        if tonumber(input) then
            return tonumber(input)
        else
            -- Try to get ID from username
            local success, id = pcall(function()
                return Players:GetUserIdFromNameAsync(input)
            end)
            if success then return id end
        end
        return nil
    end

    -- [[ UI CONSTRUCTION ]]
    -- Fungsi ini membuat UI mandiri yang mirip dengan referensi gambar
    
    local function CreateCloneUI()
        local ScreenGui = Instance.new("ScreenGui")
        ScreenGui.Name = "VanzyCloneAvatarUI"
        if gethui then ScreenGui.Parent = gethui() else ScreenGui.Parent = Services.CoreGui end
        
        -- Main Container
        local MainFrame = Instance.new("Frame", ScreenGui)
        MainFrame.Name = "MainFrame"
        MainFrame.Size = UDim2.new(0, 320, 0, 400) -- Ukuran mirip HP portrait
        MainFrame.Position = UDim2.new(0.5, -160, 0.5, -200)
        MainFrame.BackgroundColor3 = CloneConfig.Theme.Background
        MainFrame.BorderSizePixel = 0
        MainFrame.ClipsDescendants = true
        
        local MainCorner = Instance.new("UICorner", MainFrame)
        MainCorner.CornerRadius = UDim.new(0, 16)
        
        local MainStroke = Instance.new("UIStroke", MainFrame)
        MainStroke.Color = CloneConfig.Theme.Accent
        MainStroke.Thickness = 2
        MainStroke.Transparency = 0.5

        -- Header
        local Header = Instance.new("Frame", MainFrame)
        Header.Size = UDim2.new(1, 0, 0, 50)
        Header.BackgroundTransparency = 1
        
        local Title = Instance.new("TextLabel", Header)
        Title.Size = UDim2.new(1, -40, 0, 25)
        Title.Position = UDim2.new(0, 15, 0, 5)
        Title.BackgroundTransparency = 1
        Title.Text = "COPY AVATAR"
        Title.Font = Enum.Font.GothamBlack
        Title.TextColor3 = CloneConfig.Theme.Text
        Title.TextSize = 16
        Title.TextXAlignment = Enum.TextXAlignment.Left
        
        local SubTitle = Instance.new("TextLabel", Header)
        SubTitle.Size = UDim2.new(1, -40, 0, 15)
        SubTitle.Position = UDim2.new(0, 15, 0, 28)
        SubTitle.BackgroundTransparency = 1
        SubTitle.Text = "by FayintXCode"
        SubTitle.Font = Enum.Font.Gotham
        SubTitle.TextColor3 = CloneConfig.Theme.SubText
        SubTitle.TextSize = 12
        SubTitle.TextXAlignment = Enum.TextXAlignment.Left

        local CloseBtn = Instance.new("TextButton", Header)
        CloseBtn.Size = UDim2.new(0, 25, 0, 25)
        CloseBtn.Position = UDim2.new(1, -35, 0, 12)
        CloseBtn.BackgroundTransparency = 1
        CloseBtn.Text = "×"
        CloseBtn.Font = Enum.Font.Gotham
        CloseBtn.TextColor3 = CloneConfig.Theme.SubText
        CloseBtn.TextSize = 24
        
        CloseBtn.MouseButton1Click:Connect(function()
            ScreenGui:Destroy()
        end)

        -- Tabs Container
        local TabFrame = Instance.new("Frame", MainFrame)
        TabFrame.Size = UDim2.new(1, -30, 0, 35)
        TabFrame.Position = UDim2.new(0, 15, 0, 60)
        TabFrame.BackgroundColor3 = CloneConfig.Theme.ItemBG
        
        local TabCorner = Instance.new("UICorner", TabFrame)
        TabCorner.CornerRadius = UDim.new(0, 8)
        
        local ChangerBtn = Instance.new("TextButton", TabFrame)
        ChangerBtn.Size = UDim2.new(0.5, 0, 1, 0)
        ChangerBtn.BackgroundColor3 = CloneConfig.Theme.Accent -- Active state
        ChangerBtn.Text = "CHANGER"
        ChangerBtn.Font = Enum.Font.GothamBold
        ChangerBtn.TextColor3 = CloneConfig.Theme.Text
        ChangerBtn.TextSize = 12
        
        local ChangerCorner = Instance.new("UICorner", ChangerBtn)
        ChangerCorner.CornerRadius = UDim.new(0, 8)

        local FavBtn = Instance.new("TextButton", TabFrame)
        FavBtn.Size = UDim2.new(0.5, 0, 1, 0)
        FavBtn.Position = UDim2.new(0.5, 0, 0, 0)
        FavBtn.BackgroundTransparency = 1
        FavBtn.Text = "FAVORITED"
        FavBtn.Font = Enum.Font.GothamBold
        FavBtn.TextColor3 = CloneConfig.Theme.SubText
        FavBtn.TextSize = 12
        
        local FavCorner = Instance.new("UICorner", FavBtn)
        FavCorner.CornerRadius = UDim.new(0, 8)

        -- Pages
        local PageContainer = Instance.new("Frame", MainFrame)
        PageContainer.Size = UDim2.new(1, -30, 1, -110)
        PageContainer.Position = UDim2.new(0, 15, 0, 105)
        PageContainer.BackgroundTransparency = 1

        local ChangerPage = Instance.new("Frame", PageContainer)
        ChangerPage.Size = UDim2.new(1, 0, 1, 0)
        ChangerPage.BackgroundTransparency = 1

        local FavPage = Instance.new("ScrollingFrame", PageContainer)
        FavPage.Size = UDim2.new(1, 0, 1, 0)
        FavPage.BackgroundTransparency = 1
        FavPage.Visible = false
        FavPage.ScrollBarThickness = 2
        FavPage.AutomaticCanvasSize = Enum.AutomaticSize.Y
        
        local FavListLayout = Instance.new("UIListLayout", FavPage)
        FavListLayout.Padding = UDim.new(0, 8)

        -- [[ CHANGER PAGE CONTENT ]]
        
        -- Input
        local InputBox = Instance.new("TextBox", ChangerPage)
        InputBox.Size = UDim2.new(1, 0, 0, 40)
        InputBox.BackgroundColor3 = CloneConfig.Theme.ItemBG
        InputBox.Text = ""
        InputBox.PlaceholderText = "Enter Username or User ID..."
        InputBox.PlaceholderColor3 = CloneConfig.Theme.SubText
        InputBox.TextColor3 = CloneConfig.Theme.Text
        InputBox.Font = Enum.Font.Gotham
        InputBox.TextSize = 14
        
        local InputCorner = Instance.new("UICorner", InputBox)
        InputCorner.CornerRadius = UDim.new(0, 8)
        
        local InputStroke = Instance.new("UIStroke", InputBox)
        InputStroke.Color = Color3.fromRGB(40, 40, 40)
        InputStroke.Thickness = 1

        -- Action Buttons Row 1
        local CopyBtn = Instance.new("TextButton", ChangerPage)
        CopyBtn.Size = UDim2.new(0.48, 0, 0, 35)
        CopyBtn.Position = UDim2.new(0, 0, 0, 50)
        CopyBtn.BackgroundColor3 = CloneConfig.Theme.Accent
        CopyBtn.Text = "✅ COPY"
        CopyBtn.Font = Enum.Font.GothamBold
        CopyBtn.TextColor3 = Color3.new(1,1,1)
        CopyBtn.TextSize = 12
        
        local CopyCorner = Instance.new("UICorner", CopyBtn)
        CopyCorner.CornerRadius = UDim.new(0, 6)
        
        local RandomBtn = Instance.new("TextButton", ChangerPage)
        RandomBtn.Size = UDim2.new(0.48, 0, 0, 35)
        RandomBtn.Position = UDim2.new(0.52, 0, 0, 50)
        RandomBtn.BackgroundColor3 = CloneConfig.Theme.Random
        RandomBtn.Text = "🎲 RANDOM"
        RandomBtn.Font = Enum.Font.GothamBold
        RandomBtn.TextColor3 = Color3.new(1,1,1)
        RandomBtn.TextSize = 12
        
        local RandCorner = Instance.new("UICorner", RandomBtn)
        RandCorner.CornerRadius = UDim.new(0, 6)

        -- Action Buttons Row 2
        local AddFavBtn = Instance.new("TextButton", ChangerPage)
        AddFavBtn.Size = UDim2.new(1, 0, 0, 35)
        AddFavBtn.Position = UDim2.new(0, 0, 0, 95)
        AddFavBtn.BackgroundColor3 = CloneConfig.Theme.Accent
        AddFavBtn.Text = "★ ADD TO FAVORITES"
        AddFavBtn.Font = Enum.Font.GothamBold
        AddFavBtn.TextColor3 = Color3.new(1,1,1)
        AddFavBtn.TextSize = 12
        
        local AFCorner = Instance.new("UICorner", AddFavBtn)
        AFCorner.CornerRadius = UDim.new(0, 6)

        local ResetBtn = Instance.new("TextButton", ChangerPage)
        ResetBtn.Size = UDim2.new(1, 0, 0, 35)
        ResetBtn.Position = UDim2.new(0, 0, 0, 140)
        ResetBtn.BackgroundColor3 = CloneConfig.Theme.Random
        ResetBtn.Text = "♻ RESET TO ORIGINAL"
        ResetBtn.Font = Enum.Font.GothamBold
        ResetBtn.TextColor3 = Color3.new(1,1,1)
        ResetBtn.TextSize = 12
        
        local RstCorner = Instance.new("UICorner", ResetBtn)
        RstCorner.CornerRadius = UDim.new(0, 6)

        -- Footer (Discord)
        local Footer = Instance.new("Frame", ChangerPage)
        Footer.Size = UDim2.new(1, 0, 0, 40)
        Footer.Position = UDim2.new(0, 0, 1, -45)
        Footer.BackgroundColor3 = Color3.fromRGB(10, 10, 10)
        
        local FooterCorner = Instance.new("UICorner", Footer)
        FooterCorner.CornerRadius = UDim.new(0, 8)
        
        local DiscordTxt = Instance.new("TextLabel", Footer)
        DiscordTxt.Size = UDim2.new(1, 0, 0.5, 0)
        DiscordTxt.BackgroundTransparency = 1
        DiscordTxt.Text = "Join our Discord!"
        DiscordTxt.TextColor3 = Color3.fromRGB(255, 255, 255)
        DiscordTxt.Font = Enum.Font.GothamBold
        DiscordTxt.TextSize = 10
        
        local DiscordLink = Instance.new("TextLabel", Footer)
        DiscordLink.Size = UDim2.new(1, 0, 0.5, 0)
        DiscordLink.Position = UDim2.new(0, 0, 0.5, 0)
        DiscordLink.BackgroundTransparency = 1
        DiscordLink.Text = "https://discord.gg/FayintXCode"
        DiscordLink.TextColor3 = CloneConfig.Theme.Accent
        DiscordLink.Font = Enum.Font.Gotham
        DiscordLink.TextSize = 9
        
        local CopyLinkBtn = Instance.new("TextButton", Footer)
        CopyLinkBtn.Size = UDim2.new(1, 0, 1, 0)
        CopyLinkBtn.BackgroundTransparency = 1
        CopyLinkBtn.Text = ""
        
        CopyLinkBtn.MouseButton1Click:Connect(function()
            if setclipboard then
                setclipboard("https://discord.gg/FayintXCode")
                Notify("Discord", "Link copied to clipboard!")
            end
        end)

        -- [[ FAVORITES LOGIC ]]
        local function RefreshFavorites()
            -- Clear existing
            for _, v in pairs(FavPage:GetChildren()) do
                if v:IsA("Frame") then v:Destroy() end
            end
            
            for i, fav in ipairs(State.Favorites) do
                local Item = Instance.new("Frame", FavPage)
                Item.Size = UDim2.new(1, 0, 0, 50)
                Item.BackgroundColor3 = CloneConfig.Theme.ItemBG
                
                local ItemCorner = Instance.new("UICorner", Item)
                ItemCorner.CornerRadius = UDim.new(0, 6)
                
                -- Avatar Image (Headshot)
                local Img = Instance.new("ImageLabel", Item)
                Img.Size = UDim2.new(0, 35, 0, 35)
                Img.Position = UDim2.new(0, 8, 0.5, -17.5)
                Img.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
                Img.Image = "rbxthumb://type=AvatarHeadShot&id=" .. fav.id .. "&w=150&h=150"
                
                local ImgCorner = Instance.new("UICorner", Img)
                ImgCorner.CornerRadius = UDim.new(1, 0)
                
                -- Info
                local NameLbl = Instance.new("TextLabel", Item)
                NameLbl.Position = UDim2.new(0, 55, 0, 8)
                NameLbl.Size = UDim2.new(0, 150, 0, 15)
                NameLbl.BackgroundTransparency = 1
                NameLbl.Text = fav.name
                NameLbl.TextColor3 = Color3.new(1,1,1)
                NameLbl.Font = Enum.Font.GothamBold
                NameLbl.TextSize = 12
                NameLbl.TextXAlignment = Enum.TextXAlignment.Left
                
                local IdLbl = Instance.new("TextLabel", Item)
                IdLbl.Position = UDim2.new(0, 55, 0, 25)
                IdLbl.Size = UDim2.new(0, 150, 0, 15)
                IdLbl.BackgroundTransparency = 1
                IdLbl.Text = "ID: " .. fav.id
                IdLbl.TextColor3 = CloneConfig.Theme.SubText
                IdLbl.Font = Enum.Font.Gotham
                IdLbl.TextSize = 10
                IdLbl.TextXAlignment = Enum.TextXAlignment.Left
                
                -- Load Button (Invisible over text)
                local LoadBtn = Instance.new("TextButton", Item)
                LoadBtn.Size = UDim2.new(0.7, 0, 1, 0)
                LoadBtn.BackgroundTransparency = 1
                LoadBtn.Text = ""
                LoadBtn.MouseButton1Click:Connect(function()
                    ApplyAvatar(fav.id)
                end)
                
                -- Delete Button
                local DelBtn = Instance.new("TextButton", Item)
                DelBtn.Size = UDim2.new(0, 25, 0, 25)
                DelBtn.Position = UDim2.new(1, -35, 0.5, -12.5)
                DelBtn.BackgroundColor3 = CloneConfig.Theme.Random
                DelBtn.Text = "×"
                DelBtn.TextColor3 = Color3.new(1,1,1)
                DelBtn.Font = Enum.Font.GothamBold
                
                local DelCorner = Instance.new("UICorner", DelBtn)
                DelCorner.CornerRadius = UDim.new(0, 4)
                
                DelBtn.MouseButton1Click:Connect(function()
                    table.remove(State.Favorites, i)
                    SaveFavorites()
                    RefreshFavorites()
                end)
            end
        end

        -- [[ BUTTON EVENTS ]]
        
        -- Tab Switching
        ChangerBtn.MouseButton1Click:Connect(function()
            ChangerPage.Visible = true
            FavPage.Visible = false
            ChangerBtn.BackgroundColor3 = CloneConfig.Theme.Accent
            ChangerBtn.TextColor3 = CloneConfig.Theme.Text
            FavBtn.BackgroundTransparency = 1
            FavBtn.TextColor3 = CloneConfig.Theme.SubText
        end)
        
        FavBtn.MouseButton1Click:Connect(function()
            ChangerPage.Visible = false
            FavPage.Visible = true
            RefreshFavorites()
            FavBtn.BackgroundColor3 = CloneConfig.Theme.Accent
            FavBtn.BackgroundTransparency = 0
            FavBtn.TextColor3 = CloneConfig.Theme.Text
            ChangerBtn.BackgroundTransparency = 1
            ChangerBtn.BackgroundColor3 = CloneConfig.Theme.ItemBG
            ChangerBtn.TextColor3 = CloneConfig.Theme.SubText
        end)
        
        -- Copy Logic
        CopyBtn.MouseButton1Click:Connect(function()
            local input = InputBox.Text
            if input == "" then Notify("Warning", "Please enter a username or ID") return end
            
            local id = GetIdFromInput(input)
            if id then
                ApplyAvatar(id)
            else
                Notify("Error", "User not found")
            end
        end)
        
        -- Add to Favs
        AddFavBtn.MouseButton1Click:Connect(function()
            local input = InputBox.Text
            local id = GetIdFromInput(input)
            
            if id then
                -- Get Name
                local name = "Unknown"
                pcall(function() name = Players:GetNameFromUserIdAsync(id) end)
                
                -- Check duplicate
                for _, fav in ipairs(State.Favorites) do
                    if fav.id == id then Notify("Info", "Already in favorites") return end
                end
                
                table.insert(State.Favorites, {name = name, id = id})
                SaveFavorites()
                Notify("Success", "Added to favorites!")
            else
                Notify("Error", "Invalid ID/User to save")
            end
        end)
        
        -- Reset
        ResetBtn.MouseButton1Click:Connect(ResetAvatar)
        
        -- Random Player
        RandomBtn.MouseButton1Click:Connect(function()
            local playerList = Players:GetPlayers()
            if #playerList > 1 then
                local randomPlayer = playerList[math.random(1, #playerList)]
                -- Hindari diri sendiri
                if randomPlayer == LocalPlayer then
                    randomPlayer = playerList[math.random(1, #playerList)]
                end
                
                InputBox.Text = randomPlayer.Name
                ApplyAvatar(randomPlayer.UserId)
            else
                Notify("Info", "Not enough players to random")
            end
        end)

        -- Draggable
        local function makeDraggable(frame)
            local dragging, dragInput, dragStart, startPos
            frame.InputBegan:Connect(function(input)
                if input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch then
                    dragging = true
                    dragStart = input.Position
                    startPos = frame.Position
                    
                    input.Changed:Connect(function()
                        if input.UserInputState == Enum.UserInputState.End then dragging = false end
                    end)
                end
            end)
            frame.InputChanged:Connect(function(input)
                if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
                    dragInput = input
                end
            end)
            UserInputService.InputChanged:Connect(function(input)
                if input == dragInput and dragging then
                    local delta = input.Position - dragStart
                    frame.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
                end
            end)
        end
        
        makeDraggable(MainFrame)
    end

    -- [[ INTEGRATION TO VANZYXXX MENU ]]
    
    local CosmeticsTab = UI:Tab("Cosmetics")
    
    CosmeticsTab:Label("Clone Avatar Tools")
    
    CosmeticsTab:Button("OPEN CLONE AVATAR UI", CloneConfig.Theme.Accent, function()
        -- Cek jika UI sudah ada
        if Services.CoreGui:FindFirstChild("VanzyCloneAvatarUI") or (gethui and gethui():FindFirstChild("VanzyCloneAvatarUI")) then
            Notify("Info", "UI is already open!")
            return
        end
        CreateCloneUI()
    end)
    
    CosmeticsTab:Label("Quick Actions")
    
    CosmeticsTab:Input("Quick Clone (Username)", function(text)
        -- Optional: Direct clone from main menu
    end)
    
    CosmeticsTab:Button("Reset My Avatar", Color3.fromRGB(150, 40, 40), function()
        ResetAvatar()
    end)

    return CosmeticsTab -- Return tab elements for registration
end